language: node_js

node_js:
  - 'lts/*'

script:
  - 'set -e'
  - 'npm run bootstrap'
  - 'npm run lint'
  - 'npm run test'
  - 'npm run alex'

after_success:
  - 'npm run cover'
  - 'npm run cover:check'
  - 'npm run codecov'

notifications:
  email: false
