language: node_js

node_js:
  - 'lts/*'

script:
  - 'npm run bootstrap'
  - 'npm run lint'
  - 'npm run test'
  # - 'npm run cover'
  - 'npm run alex'

# after_success: 'npm run coverage:coveralls'

notifications:
  email: false
